google:
  api:
    key: AIzaSyAqQ1TZj85PWPe3Eqfm7vLfb_lByCo_qwQ
    scheme: https
    url: maps.googleapis.com/maps/api/place/nearbysearch/json

server:
  port: 8070

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SearchNearbyPlaces
    username: postgres
    password: 2211223
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
